# Copyright Advanced Micro Devices, Inc.
#
# SPDX-License-Identifier: MIT

"""Generate the playbook dropdown in the bug report issue form.

The bug report form asks which playbook a problem is about. A free-text field
gets answers we cannot route, so the options are generated from the playbooks
themselves and kept in sync by a CI check.

Only `core` and `supplemental` playbooks are listed. `backup` holds drafts that
readers cannot reach, so a bug report against one is not possible.

Usage:
    python .github/scripts/gen_issue_template_playbooks.py            # rewrite
    python .github/scripts/gen_issue_template_playbooks.py --check    # CI drift check
"""

import argparse
import difflib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
PLAYBOOKS_ROOT = REPO_ROOT / "playbooks"
FORM_PATH = REPO_ROOT / ".github" / "ISSUE_TEMPLATE" / "bug_report.yml"

CATEGORIES = ["core", "supplemental"]
BEGIN = "# BEGIN generated by .github/scripts/gen_issue_template_playbooks.py"
END = "# END generated"
INDENT = " " * 8


def collect_options() -> list[str]:
    """Return one `id - Title` option per reachable playbook, sorted by id."""
    entries = []
    for category in CATEGORIES:
        for meta_path in sorted((PLAYBOOKS_ROOT / category).glob("*/playbook.json")):
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            entries.append((meta["id"], meta["title"]))
    if not entries:
        sys.exit(f"error: no playbooks found under {PLAYBOOKS_ROOT}")
    return [f"{pid} - {title}" for pid, title in sorted(entries)]


def render(current: str, options: list[str]) -> str:
    """Splice the option list between the markers, leaving the rest untouched."""
    lines = current.splitlines(keepends=True)
    try:
        begin = next(i for i, line in enumerate(lines) if line.strip() == BEGIN)
        end = next(i for i, line in enumerate(lines) if line.strip() == END)
    except StopIteration:
        sys.exit(f"error: missing '{BEGIN}' / '{END}' markers in {FORM_PATH}")
    if end < begin:
        sys.exit(f"error: end marker precedes begin marker in {FORM_PATH}")

    # json.dumps emits a double-quoted scalar that YAML reads the same way, so a
    # title containing ": " or a leading "-" cannot break the document.
    body = [f"{INDENT}- {json.dumps(opt, ensure_ascii=False)}\n" for opt in options]
    return "".join(lines[: begin + 1] + body + lines[end:])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the form is out of date instead of rewriting it.",
    )
    args = parser.parse_args()

    options = collect_options()
    current = FORM_PATH.read_text(encoding="utf-8")
    updated = render(current, options)
    rel = FORM_PATH.relative_to(REPO_ROOT).as_posix()

    if current == updated:
        print(f"OK: {rel} lists all {len(options)} playbooks.")
        return 0

    if args.check:
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            updated.splitlines(keepends=True),
            fromfile=f"a/{rel}",
            tofile=f"b/{rel}",
        )
        print(f"ERROR: {rel} is out of date with playbooks/.")
        print("Run: python .github/scripts/gen_issue_template_playbooks.py")
        print()
        print("".join(diff), end="")
        return 1

    FORM_PATH.write_text(updated, encoding="utf-8", newline="\n")
    print(f"Updated {rel} with {len(options)} playbooks.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
